meta:
  version: 2
  flow: Classic

# DO CHANGE
DESIGN_NAME: sid
VERILOG_FILES: ["dir::src/SID_channels.v", "dir::src/SID_filter.v", "dir::src/SID_top.v", "dir::src/spi_dac_i.v", "dir::src/wrapped_sid.v", "dir::src/adc.v"]
CLOCK_PERIOD: 60
DIE_AREA: [0, 0, 550, 1000]
RUN_MAGIC_DRC: true
SYNTH_STRATEGY: AREA 1
PL_RESIZER_SETUP_SLACK_MARGIN: 0.2
GRT_RESIZER_SETUP_SLACK_MARGIN: 0.2
GRT_RESIZER_HOLD_SLACK_MARGIN: 0.2
PL_RESIZER_HOLD_SLACK_MARGIN: 0.2
PL_RESIZER_HOLD_MAX_BUFFER_PCT: 100
PNR_SDC_FILE: dir::../base.sdc
SIGNOFF_SDC_FILE: dir::../base.sdc
RUN_CTS: true
MAX_FANOUT_CONSTRAINT: 8
CLOCK_PORT: clk_i
CLOCK_NET: clk_i
VDD_NETS: ["VDD"]
GND_NETS: ["VSS"]
VERILOG_POWER_DEFINE: "USE_POWER_PINS"
RT_MAX_LAYER: Metal4
FP_PIN_ORDER_CFG: dir::pin_order.cfg
FP_PDN_MULTILAYER: false
FP_SIZING: absolute
