meta:
  version: 2
  flow: Classic
  substituting_steps:
    KLayout.DRC: null
    Checker.KLayoutDRC: null

# DO CHANGE
DESIGN_NAME: sid
VERILOG_FILES: ["dir::src/SID_channels.v", "dir::src/SID_filter.v", "dir::src/SID_top.v", "dir::src/spi_dac_i.v", "dir::src/wrapped_sid.v"]
CLOCK_PERIOD: 40
DIE_AREA: [0, 0, 925, 675]
RUN_MAGIC_DRC: true
SYNTH_STRATEGY: AREA 2
PL_RESIZER_SETUP_SLACK_MARGIN: 0.2
GRT_RESIZER_SETUP_SLACK_MARGIN: 0.2
GRT_RESIZER_HOLD_SLACK_MARGIN: 0.2
PL_RESIZER_HOLD_SLACK_MARGIN: 0.2
PL_RESIZER_HOLD_MAX_BUFFER_PCT: 100

# DO NOT CHANGE
RUN_CTS: true
MAX_FANOUT_CONSTRAINT: 8
CLOCK_PORT: clk_i
CLOCK_NET: clk_i
VDD_NETS: ["VDD"]
GND_NETS: ["VSS"]
VERILOG_POWER_DEFINE: "USE_POWER_PINS"
RT_MAX_LAYER: Metal4
FP_PIN_ORDER_CFG: dir::pin_order.cfg
FP_PDN_MULTILAYER: false
FP_SIZING: absolute
