meta:
  version: 3
  flow: Classic

RUN_LINTER: false
DESIGN_NAME: fm
VERILOG_FILES: ["dir::src/FM_channels.v", "dir::src/multiplier.v", "dir::src/multiplier_2.v", "dir::src/FM_top.v", "dir::src/wrapped_fm.v", "dir::../SID/src/adc.v", "dir::../SID/src/SID_filter.v"]
CLOCK_PERIOD: 120
DIE_AREA: [0, 0, 900, 800]
RUN_MAGIC_DRC: true
SYNTH_STRATEGY: AREA 1
PL_RESIZER_SETUP_SLACK_MARGIN: 0.3
GRT_RESIZER_SETUP_SLACK_MARGIN: 0.3
GRT_RESIZER_HOLD_SLACK_MARGIN: 0.2
PL_RESIZER_HOLD_SLACK_MARGIN: 0.2
PL_RESIZER_HOLD_MAX_BUFFER_PCT: 100
PNR_SDC_FILE: dir::../base.sdc
SIGNOFF_SDC_FILE: dir::../base.sdc
RUN_CTS: true
MAX_FANOUT_CONSTRAINT: 8
CLOCK_PORT: clk_i
CLOCK_NET: clk_i
VDD_NETS: ["VDD"]
GND_NETS: ["VSS"]
VERILOG_POWER_DEFINE: "USE_POWER_PINS"
RT_MAX_LAYER: Metal4
FP_PIN_ORDER_CFG: dir::pin_order.cfg
FP_PDN_MULTILAYER: false
FP_SIZING: absolute
