meta:
  version: 3
  flow: Classic
  substituting_steps:
    +Magic.DRC: KLayout.Antenna
    +Checker.MagicDRC: Checker.KLayoutAntenna
    +Checker.MaxCapViolations: KLayout.Render

DESIGN_NAME: gpiochip
VERILOG_FILES: ["dir::src/gpiochip.v", "dir::src/spi.v", "dir::src/uart.v"]
CLOCK_PERIOD: 25
DIE_AREA: [0, 0, 450, 450]
RUN_MAGIC_DRC: true
SYNTH_STRATEGY: DELAY 4
PL_RESIZER_SETUP_SLACK_MARGIN: 0.15
GRT_RESIZER_SETUP_SLACK_MARGIN: 0.15
GRT_RESIZER_HOLD_SLACK_MARGIN: 0.15
PL_RESIZER_HOLD_SLACK_MARGIN: 0.15
PL_RESIZER_HOLD_MAX_BUFFER_PCT: 100
DESIGN_REPAIR_TIE_FANOUT: true
DIODE_ON_PORTS: both
RUN_CTS: true
MAX_FANOUT_CONSTRAINT: 6
CLOCK_PORT: clk_i
CLOCK_NET: clk_i
PNR_SDC_FILE: dir::../base.sdc
SIGNOFF_SDC_FILE: dir::../base.sdc
VDD_NETS: ["VDD"]
GND_NETS: ["VSS"]
VERILOG_POWER_DEFINE: "USE_POWER_PINS"
RT_MAX_LAYER: Metal4
FP_PIN_ORDER_CFG: dir::pin_order.cfg
FP_PDN_MULTILAYER: false
FP_SIZING: absolute
