meta:
  version: 3
  flow: Classic

# DO CHANGE
DESIGN_NAME: misc
VERILOG_FILES: ["dir::src/misc.v", "dir::src/blinker.v", "dir::src/dice.v", "dir::src/hellorld.v", "dir::src/nano.v", "dir::src/mc.v", "dir::src/vga_demo.v", "dir::src/external/ttgf-vga-tiny-tapeout-animated-logo/src/project.v", "dir::src/external/ttgf-vga-tiny-tapeout-animated-logo/src/hvsync_generator.v", "dir::src/external/tt-waferspace-vga-screensaver/src/bitmap_rom.v", "dir::src/external/tt-waferspace-vga-screensaver/src/gamepad_pmod.v", "dir::src/external/tt-waferspace-vga-screensaver/src/palette.v", "dir::src/external/tt-waferspace-vga-screensaver/src/tt_um_waferspace_vga_screensaver.v", "dir::src/external/tt-waferspace-vga-screensaver/src/vga_sync_generator.v"]
CLOCK_PERIOD: 35
DIE_AREA: [0, 0, 525, 1000]
RUN_MAGIC_DRC: true
SYNTH_STRATEGY: AREA 0
PL_RESIZER_SETUP_SLACK_MARGIN: 0.25
GRT_RESIZER_SETUP_SLACK_MARGIN: 0.25
GRT_RESIZER_HOLD_SLACK_MARGIN: 0.1
PL_RESIZER_HOLD_SLACK_MARGIN: 0.1
PL_RESIZER_HOLD_MAX_BUFFER_PCT: 100

RUN_CTS: true
CLOCK_PORT: clk_i
CLOCK_NET: clk_i
PNR_SDC_FILE: dir::../base.sdc
SIGNOFF_SDC_FILE: dir::../base.sdc
VDD_NETS: ["VDD"]
GND_NETS: ["VSS"]
VERILOG_POWER_DEFINE: "USE_POWER_PINS"
RT_MAX_LAYER: Metal4
FP_PIN_ORDER_CFG: dir::pin_order.cfg
FP_PDN_MULTILAYER: false
FP_SIZING: absolute

# Remove everything between this comment end the one below to disable use of the custom DFF cells
LIB:
  "*_tt_025C_5v00": ["pdk_dir::libs.ref/gf180mcu_fd_sc_mcu7t5v0/lib/gf180mcu_fd_sc_mcu7t5v0__tt_025C_5v00.lib", "pdk_dir::libs.ref/gf180mcu_fd_io/lib/gf180mcu_fd_io__tt_025C_5v00.lib", "dir::gf180mcu_as_ex_mcu7t5v0/lib/gf180mcu_as_ex_mcu7t5v0__tt_025C_5v00.lib"]
  "*_ss_125C_4v50": ["pdk_dir::libs.ref/gf180mcu_fd_sc_mcu7t5v0/lib/gf180mcu_fd_sc_mcu7t5v0__ss_125C_4v50.lib", "pdk_dir::libs.ref/gf180mcu_fd_io/lib/gf180mcu_fd_io__ss_125C_4v50.lib", "dir::gf180mcu_as_ex_mcu7t5v0/lib/gf180mcu_as_ex_mcu7t5v0__ss_125C_4v50.lib"]
  "*_ff_n40C_5v50": ["pdk_dir::libs.ref/gf180mcu_fd_sc_mcu7t5v0/lib/gf180mcu_fd_sc_mcu7t5v0__ff_n40C_5v50.lib", "pdk_dir::libs.ref/gf180mcu_fd_io/lib/gf180mcu_fd_io__ff_n40C_5v50.lib", "dir::gf180mcu_as_ex_mcu7t5v0/lib/gf180mcu_as_ex_mcu7t5v0__ff_n40C_5v50.lib"]
CELL_LEFS: ["pdk_dir::libs.ref/gf180mcu_fd_sc_mcu7t5v0/lef/gf180mcu_fd_sc_mcu7t5v0.lef", "dir::gf180mcu_as_ex_mcu7t5v0/lef/gf180mcu_as_ex_mcu7t5v0.lef"]
CELL_GDS: ["pdk_dir::libs.ref/gf180mcu_fd_sc_mcu7t5v0/gds/gf180mcu_fd_sc_mcu7t5v0.gds", "dir::gf180mcu_as_ex_mcu7t5v0/gds/gf180mcu_as_ex_mcu7t5v0__dfxtp_2.gds", "dir::gf180mcu_as_ex_mcu7t5v0/gds/gf180mcu_as_ex_mcu7t5v0__dfxtn_2.gds"]
CELL_VERILOG_MODELS: ["pdk_dir::libs.ref/gf180mcu_fd_sc_mcu7t5v0/verilog/gf180mcu_fd_sc_mcu7t5v0.v", "pdk_dir::libs.ref/gf180mcu_fd_sc_mcu7t5v0/verilog/primitives.v", "dir::gf180mcu_as_ex_mcu7t5v0/verilog/gf180mcu_as_ex_mcu7t5v0.v"]
CELL_SPICE_MODELS: ["pdk_dir::libs.ref/gf180mcu_fd_sc_mcu7t5v0/spice/gf180mcu_fd_sc_mcu7t5v0.spice", "dir::gf180mcu_as_ex_mcu7t5v0/cds/gf180mcu_as_ex_mcu7t5v0.spice"]

EXTRA_EXCLUDED_CELLS: ["gf180mcu_fd_sc_mcu7t5v0__dff*"]
#End
