meta:
  version: 3
  flow: Classic
  substituting_steps:
    OpenROAD.Resizertimingpostcts: null
    OpenROAD.CTS: null
    OpenROAD.RepairDesignPostGPL: null
    OpenROAD.STAMidPnr: null
    +Magic.DRC: KLayout.Antenna
    +Checker.MagicDRC: Checker.KLayoutAntenna
    +Checker.MaxCapViolations: KLayout.Render

DESIGN_NAME: repeater
VERILOG_FILES: dir::src/repeater.v
CLOCK_PERIOD: 20
DIE_AREA: [0, 0, 200, 200]
RUN_MAGIC_DRC: true
MAX_FANOUT_CONSTRAINT: 4
MAX_TRANSITION_CONSTRAINT: 0.7
DESIGN_REPAIR_TIE_FANOUT: true
DIODE_ON_PORTS: both
CLOCK_PORT: clk_i
CLOCK_NET: clk_i
VDD_NETS: ["VDD"]
GND_NETS: ["VSS"]
VERILOG_POWER_DEFINE: "USE_POWER_PINS"
RT_MAX_LAYER: Metal4
FP_PIN_ORDER_CFG: dir::pin_order.cfg
FP_PDN_MULTILAYER: false
FP_SIZING: absolute
PNR_SDC_FILE: dir::base.sdc
SIGNOFF_SDC_FILE: dir::base.sdc
STD_CELL_LIBRARY: gf180mcu_fd_sc_mcu9t5v0
OUTPUT_CAP_LOAD: 200
FP_IO_HLAYER: Metal3
FP_IO_VLAYER: Metal4
