meta:
  version: 2
  flow: Classic
  substituting_steps:
    OpenROAD.Resizertimingpostcts: null
    OpenROAD.CTS: null
    OpenROAD.RepairDesignPostGPL: null
    OpenROAD.STAMidPnr: null

# DO CHANGE
DESIGN_NAME: multiplexer
VERILOG_FILES: dir::src/mux.v
CLOCK_PERIOD: 23
DIE_AREA: [0, 0, 700, 800]
RUN_MAGIC_DRC: true
SYNTH_STRATEGY: DELAY 4
PL_TARGET_DENSITY: 0.12
PL_RESIZER_SETUP_SLACK_MARGIN: 0
GRT_RESIZER_SETUP_SLACK_MARGIN: 0
GRT_RESIZER_HOLD_SLACK_MARGIN: 0
PL_RESIZER_HOLD_SLACK_MARGIN: 0
MAX_FANOUT_CONSTRAINT: 7
CLOCK_PORT: clk_i
CLOCK_NET: clk_i
VDD_NETS: ["VDD"]
GND_NETS: ["VSS"]
VERILOG_POWER_DEFINE: "USE_POWER_PINS"
RT_MAX_LAYER: Metal4
FP_PIN_ORDER_CFG: dir::pin_order.cfg
FP_PDN_MULTILAYER: false
FP_SIZING: absolute
STD_CELL_LIBRARY: gf180mcu_fd_sc_mcu9t5v0
