meta:
  version: 2
  flow: Classic
  substituting_steps:
    KLayout.DRC: null
    Checker.KLayoutDRC: null
    OpenROAD.Resizertimingpostcts: null
    OpenROAD.CTS: null
    OpenROAD.RepairDesignPostGPL: null
    OpenROAD.STAMidPnr: null

# DO CHANGE
DESIGN_NAME: multiplexer
VERILOG_FILES: dir::src/mux.v
CLOCK_PERIOD: 20
DIE_AREA: [0, 0, 600, 600]
RUN_MAGIC_DRC: true
SYNTH_STRATEGY: DELAY 4
PL_RESIZER_SETUP_SLACK_MARGIN: 0
GRT_RESIZER_SETUP_SLACK_MARGIN: 0
GRT_RESIZER_HOLD_SLACK_MARGIN: 0
PL_RESIZER_HOLD_SLACK_MARGIN: 0
MAX_FANOUT_CONSTRAINT: 4
MAX_TRANSITION_CONSTRAINT: 0.7
CLOCK_PORT: clk_i
CLOCK_NET: clk_i
VDD_NETS: ["VDD"]
GND_NETS: ["VSS"]
VERILOG_POWER_DEFINE: "USE_POWER_PINS"
RT_MAX_LAYER: Metal4
FP_PIN_ORDER_CFG: dir::pin_order.cfg
FP_PDN_MULTILAYER: false
FP_SIZING: absolute
